---
- hosts: all
  become: yes
  become_user: root
  roles:
    - install-dependency

- hosts: masters
  become: yes
  become_user: root
  gather_facts: false
  roles: 
    - masters

- hosts: workers
  become: yes
  become_user: root
  roles:
    - workers
    